### ISSUE TITLE
It does not work on Windows

### ISSUE THREAD

**Issue by roozbehsayadi** [mhezarei/netusage#1]
Hi.
In your REAMDE, you said that the code runs on Windows too, but it does not. the _fcntl_ library only works on Linux.
If you want to make it work on Windows, you should use _win32api_ library. Note that it works completely different from _fcntl_.

**Comment by mhezarei** [comment]
Hello. 
Thank you so much. I will edit the README and later on find a way to make it work on other operating systems.
